version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "blue"
template = "{{ .Path }} "

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "darkGray"
background = "transparent"
template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{ end }} "

[blocks.segments.properties]
fetch_status = true
commit_icon = "@"
branch_icon = ""

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{ if gt .Code 0 }}red{{ end }}",
  "{{ if eq .Code 0 }}white{{ end }}",
]
template = "{{ if gt .Code 0 }}⨯{{ else }}›{{ end }}"

[[blocks]]
type = "rprompt"
overflow = "hidden"

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "yellow"

[blocks.segments.properties]
threshold = 5000
style = "round"

[transient_prompt]
foreground = "white"
template = "› "
